version: '3'
services:
  mongo:
    image: mongo:4
    container_name: mongodb
    environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - "27017:27017"
    volumes:
      - "~/dockerdata/mongo:/data/db"
      - "./mongo-entrypoint/:/docker-entrypoint-initdb.d/"
      - ./mongo.conf:/etc/mongo.conf
      - ~/dockerdata/log/mongo:/data/mongodb/logs
    command: mongod
    networks: 
      - elk

networks:
  elk:
    external: true