version: '3'
services:
  nginx: 
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./wifidns.top.conf:/etc/nginx/conf.d/wifidns.top.template
      - ~/dockerdata/log/nginx/:/var/log/nginx/
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443
    networks:
      - nginx
    env_file:
      - ./common.env
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/wifidns.top.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
networks:
  nginx:
    external:
      name: metricbeat