version: '3'
services:
  elk:
    container_name: elk
    image: sebp/elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    restart: always
    # environment:
    #   - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - ~/dockerdata/elk:/var/lib/elasticsearch
